# Generated by Django 4.1.7 on 2023-02-28 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=1000)),
                ('product_category', models.CharField(max_length=1000)),
                ('product_description', models.TextField(max_length=20000)),
                ('Product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_count', models.IntegerField()),
            ],
        ),
    ]
