# Generated by Django 4.1.7 on 2023-02-28 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=50)),
                ('shipping_adress', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
